### ISSUE TITLE
Form submits even though captcha is not checked but with error response

### ISSUE THREAD

**Issue by ryanfern86goa** [silverstripe/silverstripe-spamprotection#69]
Hi,

I'm using your module along with https://github.com/chillu/silverstripe-recaptcha/tree/2.0.

I have added the spam protection field to the form and have it displaying correctly on frontend.
The form is submitted through ajax using userforms/javascript/UserForm.js. 

User should not be able to submit the form if the google re-captcha is not selected  but it does even if I don't select it but with a error message response form in the network tab.

Any Help ?

Thanks

**Comment by NightJar** [comment]
Hi, thanks for taking the time to post to our issue tracker.

The issue tracker is reserved for reporting bugs and we don't provide support via the issue tracker. There are great [community support options](http://www.silverstripe.org/community/#introduction) where you can get help including [our forum](https://forum.silverstripe.org), [Stack Overflow (remember to tag as silverstripe)](http://stackoverflow.com/questions/tagged/silverstripe) and even [Slack](http://silverstripe.org/slack).

With that said this sounds like it _could_ be an issue lying underneath - in which case I encourage you to please provide a little more information about your problem - such as what versions of all the relevant modules you are using, and how we may replicate the issue in order to correctly patch the bug.

You can get information about what modules are installed by using `composer show` - probably `composer show | grep silverstripe` is best for brevity :)

Any useful information you can provide is always helpful - e.g. does the submission fail as expected when you do _not_ use the `userforms.js`? (i.e. with javascript disabled).

If you'd like some guidance on how to fix this yourself and make a contribution to the project please feel free to ask - the aforementioned slack community has a `get-involved` channel set up just for such guidance.

**Comment by robbieaverill** [comment]
Please feel free to reopen with further supporting information
