### ISSUE TITLE
Allow disabling spam protection on dev sites

### ISSUE THREAD

**Issue by jinjie** [silverstripe/silverstripe-spamprotection#78]
Add a new feature that allow site wide disabling of spam protection.

For example to provide a new configuration like

```yml
SilverStripe\SpamProtection\Extension:
  disable_environment_type:
    - dev
```

`FormSpamProtectionExtension::enableSpamProtection()` will then be ignored on `dev` environments

**Comment by maxime-rainville** [comment]
I'm personally always a bit reticent to introduce different logic in dev environment vs live environment. You make it more likely that someone will end up wasting time trying to understand why the SPAM protection isn't working in their DEV environment or you might miss a bug that only occurs on the LIVE site because some bit of logic is only enabled there.

You might be able to achieve the result you want without updating the module with some clever use of [configuration exclusionary rules](https://docs.silverstripe.org/en/4/developer_guides/configuration/configuration/#exclusionary-rules).

**Comment by jinjie** [comment]
Having developed on SS so many years now, have never used exclusionary rules! Thanks for the heads up and new reading materials for me.

I also do agree with your thoughts. Closing this issue since this can be done with exclusionary rules.
